image:
  repository: ghcr.io/kadense/kadense
  tag: latest

jupyternetes:
  pods:
    operator:
      enabled: true
      image:
        repository: ""
        name: jupyternetes-pods-operator
        tag: ""
        pullPolicy: Always
      serviceAccount:
        create: true
        name: ""
      nodeSelector: {}
      tolerations: []
      affinity: {}
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  pod:
    status:
      operator:
        image:
          repository: ""
          name: jupyternetes-podstatus-operator
          tag: ""
          pullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  pvcs:
    operator:
      enabled: true
      image:
        repository: ""
        name: jupyternetes-pvcs-operator
        tag: ""
        pullPolicy: Always
      serviceAccount:
        create: true
        name: ""
      nodeSelector: {}
      tolerations: []
      affinity: {}
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  template:
    name: default-template
    spec:
      pods:
      - name: notebook
        labels:
          jupyternetes.kadense.io/userId: '{jupyterhub.user.id}'
        spec:
          containers:
          - name: notebook
            image: quay.io/jupyter/datascience-notebook:hub-5.2.1
            env:
            - name: JPY_API_TOKEN
              value: '{jupyterhub.api_token}'
            - name: JUPYTERHUB_ACTIVITY_URL
              value: 'http://hub.{jupyterhub.namespace}.svc.cluster.local:8081/hub/api/users/{jupyterhub.user.name}/activity'
            - name: JUPYTERHUB_ADMIN_ACCESS
              value: "1"
            - name: JUPYTERHUB_API_TOKEN
              value: '{jupyterhub.api_token}'
            - name: JUPYTERHUB_API_URL
              value: http://hub.{jupyterhub.namespace}.svc.cluster.local:8081/hub/api
            - name: JUPYTERHUB_BASE_URL
              value: /
            - name: JUPYTERHUB_CLIENT_ID
              value: '{jupyterhub.oauth_client_id}'
            - name: JUPYTERHUB_COOKIE_HOST_PREFIX_ENABLED
              value: "0"
            - name: JUPYTERHUB_HOST
            - name: JUPYTERHUB_OAUTH_ACCESS_SCOPES
              value: '["access:servers!server={jupyterhub.user.name}/", "access:servers!user={jupyterhub.user.name}"]'
            - name: JUPYTERHUB_OAUTH_CALLBACK_URL
              value: /user/{jupyterhub.user.name}/oauth_callback
            - name: JUPYTERHUB_OAUTH_CLIENT_ALLOWED_SCOPES
              value: '[]'
            - name: JUPYTERHUB_OAUTH_SCOPES
              value: '["access:servers!server={jupyterhub.user.name}/", "access:servers!user={jupyterhub.user.name}"]'
            - name: JUPYTERHUB_PUBLIC_HUB_URL
            - name: JUPYTERHUB_PUBLIC_URL
            - name: JUPYTERHUB_SERVER_NAME
            - name: JUPYTERHUB_SERVICE_PREFIX
              value: '/user/{jupyterhub.user.name}/'
            - name: JUPYTERHUB_SERVICE_URL
              value: 'http://0.0.0.0:8888/user/{jupyterhub.user.name}/'
            - name: JUPYTERHUB_USER
              value: '{jupyterhub.user.name}'
            - name: JUPYTER_IMAGE
              value: quay.io/jupyter/datascience-notebook:hub-5.2.1
            - name: JUPYTER_IMAGE_SPEC
              value: quay.io/jupyter/datascience-notebook:hub-5.2.1
            - name: MEM_GUARANTEE
              value: "1073741824"
            volumeMounts:
            - name: workspace-pvc
              mountPath: '/home/{jupyterhub.user.name}/work'
            ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          volumes:
          - name: workspace-pvc
            persistentVolumeClaim:
              claimName: '{jupyternetes.pvcs.workspace}'
      pvcs:
      - name: workspace
        labels:
          jupyternetes.kadense.io/userId: '{jupyterhub.user.id}'
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi    