{{- if .Values.jupyternetes.pvcs.operator.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jupyternetes.pvcs.operator.fullname" . }} 
rules:
- apiGroups: [ "kadense.io" ]
  resources: ["jupyternotebookinstances", "jupyternotebooktemplates", "jupyternotebookinstances/status", "jupyternotebooktemplates/status"]
  verbs: [ "get", "list", "watch" ]

- apiGroups: [ "kadense.io" ]
  resources: [ "jupyternotebookinstances/status"]
  verbs: [ "patch" ]

- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumeclaims/status"]
  verbs: ["get", "list", "create", "delete"]

{{- end -}}