### The core permissions needed for most operators to function
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.role" . }}
rules:
# Core Read
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list"]

# CRD Read
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","list","watch"]

# Framework: admission webhook configuration management.
- apiGroups: ["admissionregistration.k8s.io/v1", "admissionregistration.k8s.io/v1beta1"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["create", "patch"]

# Events  
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
