apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jupyternetes.pods.operator.fullname" . }}:{{ include "jupyternetes.pods.operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jupyternetes.pods.operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jupyternetes.pods.operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jupyternetes.pods.operator.fullname" . }}:{{ include "operator.role" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.role" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jupyternetes.pods.operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}