{{- if .Values.jupyternetes.pods.operator.enabled -}}
{{- if .Values.jupyternetes.pods.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyternetes.pods.operator.serviceAccountName" . }}
{{- end -}}
{{- end -}}
