name: Create Release Packages

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

permissions:
  packages: write
  contents: write
  id-token: write
  pages: write

jobs:
  setup:
    name: setup
    needs: []
    runs-on: ubuntu-latest
    outputs:
        config: ${{ steps.config.outputs.config }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: config
      run: |
        BUILD_CONFIG=$(yq -p yaml -o json build-config.yaml | jq -c)

        echo "$BUILD_CONFIG"
        echo "config=$BUILD_CONFIG" >> $GITHUB_OUTPUT


  get-version:
    needs: []
    uses: kadense/kadense/.github/workflows/semver.yaml@main
    secrets: inherit 
  
  container-images:
    uses: kadense/kadense/.github/workflows/container-images.yaml@main
    needs: 
    - get-version
    - setup
    secrets: inherit 
    with:
      GitVersion_SemVer: ${{ needs.get-version.outputs.GitVersion_SemVer }}
      Config: ${{ needs.setup.outputs.config }} 
  
  publish-helm-chart:
    uses: kadense/kadense/.github/workflows/publish-helm-chart.yaml@main
    secrets: inherit
    needs:
    - get-version
    - setup
    - container-images
    with:
      GitVersion_SemVer: ${{ needs.get-version.outputs.GitVersion_SemVer }}
      Config: ${{ needs.setup.outputs.config }} 
  
  publish-to-pypi:
    uses: kadense/kadense/.github/workflows/publish-pypi.yaml@main
    secrets: inherit
    needs: 
    - get-version
    - setup
    - container-images
  
  publish-to-nuget:
    uses: kadense/kadense/.github/workflows/publish-nuget.yaml@main
    secrets: inherit
    needs: 
    - get-version
    - setup
    - container-images

  publish-ghp:
    uses: kadense/kadense/.github/workflows/publish-ghp.yaml@main
    secrets: inherit
    needs: 
    - get-version
    - setup
    - container-images
        
  # publish-python-packages:
  #   uses: kadense/kadense/.github/workflows/python-modules.yaml@main
  #   secrets: inherit
  #   needs:
  #   - get-version
  #   - setup
  #   with:
  #     GitVersion_SemVer: ${{ needs.get-version.outputs.GitVersion_SemVer }}
  #     Config: ${{ needs.setup.outputs.config }} 
  